<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Fishman;

class PagesController extends Controller
{
    /**
    *Function to direct the administrator.
    *
    *@return the view generated by the aforementioned function.
    */
    public function admin()
    {
        return view('projects.index');
    }
    /**
    *Function to delete a fisherman based on the id given.
    *
    *@return redirects to show the results.
    */
    public function delete($id)
    {
        $project= Fishman::find($id)->delete();

        return redirect('/project');
    }
    /**
    *Function that shows all the fishermen.
    *
    *@return a compact view to show all data recovered by the function.
    */
    public function show()
    {
        $project= Fishman::all();


        return view('projects.fishman', compact('project'));
    }
    /**
    *This will be a function to take the administrator to the chat.
    *
    *@return void.
    */
    public function chat()
    {
        dd('hola');
    }
    /**
    *Function to edit the user by the administrator.
    *
    *@return the view that lets the administrator edit an specific user.
    */
    public function edit($id)
    {
        $project= Fishman::find($id);
        return view('projects.edit', compact('project'));
    }

    /**
    *Function to update a Place in the Places table.
    *
    *@return a redirection to the table with the updated Place.
    */
    public function update($id)
    {
        $project= Fishman::find($id);
        $project->Place=request('Place');       
        $project->save();   
        return redirect("/project/{$project->id}");
    }
    /**
    *Function to create a new table.
    *
    *@return a view create inside projects.
    */
    public function create()
    {
        return view('projects.create');
    }
    /**
    *Function to create a new fisherman.
    *
    *@return a redirection to the table with the updated user.
    */
    public function user()
    {
        $project = new Fishman();        
        $project->Name=request('Name');
        $project->Phone=request('Phone');
        $project->User=request('User');
        $project->Password=request('Password');
        $project->save();
        return redirect('/project');
    }
    /**
    *Function to find an specific fisherman.
    *
    *@return returns the Captain view inside Projects.
    */
    public function fishman($id)
    {
        $project= Fishman::find($id);
        return view('projects.captain', compact('project'));
    }
    /**
    *Function to take a fisherman to the chat.
    *
    *@return a redirection to the chat.
    */
    public function fishmanChat($id)
    {
        $project= Fishman::find($id);
        return view('projects.fishmanChat', compact('project'));
    }
}
